### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/health-inequalities-notebook#1]
It might be worth dropping the "QuartoBook" from the name as this describes how it's been built rather than what it contains. Perhaps then expanding on HIQ to `health-inqualities-notebook` or something similar?

**Comment by ThomUK** [comment]
I would agree with the rename that you propose Zoe.

It might be good to rename the other repo too (https://github.com/nhs-r-community/mdsn-collab), so that they are more clearly linked.

**Comment by Lextuga007** [comment]
Have you changed this locally to your laptop? The name here will need to be changed in GitHub itself (which you are very welcome to do 😄 ) in the Settings tab and it's the very first option to change at the top. The `.Rproj` will still work with the old name but useful to change and that can be done by creating a new branch locally or from GitHub (on the right side of this page there is a `Development` section above `Notifications` where it says `Create a branch`) or use the packages {usethis} and {gert}, change the name and then push to GitHub where you can set up a pull request.

If you like to use {usethis} and {gert} the code I use for this workflow is:

```
usethis::pr_init("1-rename-proj") # creates a pr and branch locally
```
Make the change

```
gert::git_commit_all("Updated .RProj name")
usethis::pr_push()
```

And then the GitHub pull request page will open on your browser where you can finish submitting the PR (often clicking on the green buttons).

**Comment by AlWatson20** [comment]
I think it has worked using the use this commands.

**Comment by Lextuga007** [comment]
Would it be ok to drop the `HIQ_` from the name? It's not a usual acronym (yet!) so might cause confusion in searches.

**Comment by AlWatson20** [comment]
Yes, changed in the settings menu in github

**Comment by Lextuga007** [comment]
That was fast! Thank you 👍🏻

**Comment by francisbarton** [comment]
Sorry to be a total PITA but can we fix the typo in the project & repo name?
It says 'inequalites' instead of 'inequalities', currently.

**Comment by ThomUK** [comment]
Eagle eyes goes to @francisbarton. 
While fixing, the final URL in the readme is now out of date.  Github redirects it OK, but it would be good to update for clarity.

**Comment by Lextuga007** [comment]
Great spots @francisbarton and @ThomUK and perfect examples of team work! 🏆
