### ISSUE TITLE
Write a page giving an overview of Indices of Multiple Deprivation (IMD)

### ISSUE THREAD

**Issue by ThomUK** [nhs-r-community/health-inequalities-notebook#13]
Possible sources:
https://en.wikipedia.org/wiki/Multiple_deprivation_index
https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019

Mapping:
https://www.gov.uk/guidance/english-indices-of-deprivation-2019-mapping-resources

Live map:
http://dclgapps.communities.gov.uk/imd/iod_index.html

**Comment by francisbarton** [comment]
I'm really interested in the IMD and what it does and doesn't do, so I'd be up for making a start on this page... when I get round to it :-)

**Comment by Lextuga007** [comment]
Need to add Tom's original links

**Comment by Lextuga007** [comment]
Move the `other links` https://github.com/nhs-r-community/health-inequalities-notebook/blob/e1f5ca7e39b911d107129926e781ef206b5e0a68/content/imd.qmd#L149 to open-analytics-resources and then link back.

**Comment by Lextuga007** [comment]
Trying to get to the bottom of why LSOA codes can appear in datasets as either starting with an E or an S I found this https://www.warrington.gov.uk/sites/default/files/2019-09/english-indices-of-deprivation-2015-frequently-asked-questions.pdf which although it is on the Warrington.gov.uk site is a Dept for Communities and Local Government document.

**Comment by francisbarton** [comment]
Hi Zoë, where are you finding S codes in the datasets? An S code will be in Scotland (and they don't have LSOAs, they have Data Zones).

**Comment by Lextuga007** [comment]
That's what I'm starting to conclude! I think I'm looking at Scotland's data!

```
api_url <- "https://services1.arcgis.com/ESMARspQHYMw9BZ9/ArcGIS/rest/services/Online_ONS_Postcode_Directory_Live/FeatureServer/0/query"
query_params <- list(
  where = "LSOA11 LIKE '%'",
  outFields = "*",
  returnCountOnly = FALSE,
  returnDistinctValues = TRUE,
  f = "json"
)

# Make the API request
response <- httr::GET(api_url, query = query_params)

# Parse the JSON response
data <- jsonlite::fromJSON(httr::content(response, "text"))

# Create as dataframe
df <- data.frame(data$features$attributes)

df
```

**Comment by johnmackintosh** [comment]
https://www.gov.scot/collections/scottish-index-of-multiple-deprivation-2020/
Some useful background info on the SIMD and links to data. 
I have done some maps/other visualisations on my blog in the past if you are interested

**Comment by Lextuga007** [comment]
That's great! You've got a few charts that are really nice and I see you've tagged the blogs too! https://johnmackintosh.net/tag-deprivation/

Thanks 🙇🏻

**Comment by Lextuga007** [comment]
@all-contributors please add @johnmackintosh for content
