### ISSUE TITLE
Remove renv files

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/health-inequalities-notebook#24]

**Comment by Lextuga007** [comment]
Tried this but realised the gh-action refers to renv so reverted PR and updated renv.

**Comment by ThomUK** [comment]
renv is causing me some issues with contributing to this repo.  I don't routinely use renv, so am not sure how to.  I get renv errors when rendering the book locally though, so I'm struggling to contribute.  Do you have any advice @Lextuga007?

**Comment by ThomUK** [comment]
For anyone else with similar issues, `renv::deactivate()` allowed me to render and work locally.  The project doesn't seem to need the packages renv is trying to install.

**Comment by Lextuga007** [comment]
All removed 😃
