### ISSUE TITLE
Add link to NHSE's statement on information on health inequalities

### ISSUE THREAD

**Issue by DCEW** [nhs-r-community/health-inequalities-notebook#55]
https://www.england.nhs.uk/long-read/nhs-englands-statement-on-information-on-health-inequalities-duty/

**Comment by Lextuga007** [comment]
Thank you for this suggestion!

This could go in the [Background literature chapter](https://health-inequalities.nhsrcommunity.com/content/background_literature.html). I'm happy to add this but if you'd like to have a go with Quarto/Git I can help with that too.
